### ISSUE TITLE
Include latest version of OSGi-Testsuite in repository

### ISSUE THREAD

**Issue by rherrmann** [fappel/test-libraries#1]
This would allow to eliminate references to the OSGi-Testsuite repository from most of our target definitions.

**Comment by fappel** [comment]
Since I think this is fixed with commit 55d9c6053809dbc54131750439551913f8d14254 I will close this issue. Feel free to reopen if I'm missing something.

**Comment by rherrmann** [comment]
Works! I can see the 1.2 version of the OSGi TestSuite.
